---
networks:
  caddy:
    name: caddy-network

volumes:
  media_music:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/music"

#secrets:

services:
  navidrome:
    image: deluan/navidrome:latest@sha256:2ae037d464de9f802d047165a13b1c9dc2bdbb14920a317ae4aef1233adc0a3c
    user: 1000:1000
    pull_policy: ${pull_policy}
    container_name: ${navidrome_container_name}
    restart: ${restart}
    networks:
      - caddy
    ports:
      - "${navidrome_port_4533}:4533"
    environment:
      - ND_SCANNER_PURGEMISSING=full
    volumes:
      - /docker/${navidrome_container_name}/data:/data
      - media_music:/music:ro

