services:
  gluetun_downloaders:
    image: qmcgaw/gluetun:latest@sha256:791a15decc982d4968d10159227cca26e12083b7e51b00b2c3d0e35163203a69
    pull_policy: ${pull_policy}
    container_name: ${gluetun_downloaders_container_name}
    restart: ${restart}
    networks:
      mediarr:
        ipv4_address: 10.20.20.20
    ports:
      - ${qbittorrent_port_ui}:${qbittorrent_port_ui}
      - ${sabnzbd_port_ui}:${sabnzbd_port_ui}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - GLUETUN_HTTP_CONTROL_SERVER_ENABLE=on
      - WIREGUARD_PRIVATE_KEY=${MEDIARR_WG_PRIVATE_KEY_DOWNLOADERS}
      - WIREGUARD_ADDRESSES=${MEDIARR_WG_ADDRESSES}
      - SERVER_COUNTRIES=Switzerland
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${qbittorrent_port_ui}/api/v2/app/setPreferences 2>&1'
    volumes:
      - /docker/${gluetun_downloaders_container_name}/config:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:51dd497bd9b1de06fc1f9c9753297fae1e7445ad817e4528ee3f84c9c3122c7d
    pull_policy: ${pull_policy}
    container_name: ${qbittorrent_container_name}
    restart: ${restart}
    depends_on:
      - gluetun_downloaders
    network_mode: "service:gluetun_downloaders"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=${qbittorrent_port_ui}
    volumes:
      - /docker/qbittorrent/config:/config
      - qb_downloads:/docker/downloads/torrent

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest@sha256:37fc318dc632106eac00f096661f43ca513793bf51913bcbd989ba921b3409c8
    pull_policy: ${pull_policy}
    container_name: ${sabnzbd_container_name}
    restart: ${restart}
    depends_on:
      - gluetun_downloaders
    network_mode: "service:gluetun_downloaders"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/sabnzbd/config:/config
      - /docker/downloads/usenet/inprogress:/docker/downloads/usenet/inprogress
      - /docker/downloads/usenet/complete:/docker/downloads/usenet/complete
