---
networks:
  mediarr:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.20.20.0/24

volumes:
  media_tvshows:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/tvshows"
  media_movies:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/movies"
  jellyfin_config:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${jellyfin_container_name}/config"
  prowlarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${prowlarr_container_name}/config"
  qbittorrent_config:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${qbittorrent_container_name}/config"
  qbittorrent_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${qbittorrent_container_name}/downloads"


#secrets:

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest@sha256:dc7e75b48d038185216e00029c60a7860c557a0563811934d4870c875467ea8a
    pull_policy: ${pull_policy}
    container_name: ${jellyfin_container_name}
    restart: ${restart}
    networks:
      mediarr:
        ipv4_address: 10.20.20.5
    ports:
      - ${jellyfin_port_8096}:8096
    environment: 
      - UID=1000
      - GID=1000
      - TZ=America/Chicago
    volumes:
      - jellyfin_config:/config
      - media_tvshows:/data/tvshows
      - media_movies:/data/movies
    devices:
      - /dev/dri:/dev/dri

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    pull_policy: ${pull_policy}
    container_name: ${flaresolverr_container_name}
    restart: ${restart}
    networks:
      mediarr:
        ipv4_address: 10.20.20.15
    ports:
      - ${flaresolverr_port_8191}:8191
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: ${pull_policy}
    container_name: ${qbittorrent_container_name}
    restart: ${restart}
    networks:
      mediarr:
        ipv4_address: 10.20.20.20
    ports:
      - ${qbittorrent_port_8080}:8080
      - ${qbittorrent_port_6881}:6881
      - ${qbittorrent_port_6881}:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_config:/config
      - qbittorrent_downloads:/downloads

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    pull_policy: ${pull_policy}
    container_name: ${prowlarr_container_name}
    restart: ${restart}
    depends_on:
      - flaresolverr
      - qbittorrent
    networks:
      mediarr:
        ipv4_address: 10.20.20.10
    ports:
      - ${prowlarr_port_9696}:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - prowlarr_config:/config




