---
include:
  - ../components/caddy_network.yaml
  - downloaders.yaml
  - finders.yaml

#networks:

volumes:
  qb_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/downloads/torrent"
  media_tvshows:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/tvshows"
  media_movies:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/movies"
  media_music:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/music"

#secrets:

services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    pull_policy: ${pull_policy}
    container_name: ${homarr_container_name}
    restart: ${restart}
    networks:
      - caddy
    ports:
      - ${homarr_port_7575}:7575
    volumes:
      - /docker/${homarr_container_name}/appdata:/appdata

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest@sha256:0ffe47d268e9cb2665f52e56fd7756ed984b0f3e7eddaf3882ebdb677af1b341
    pull_policy: ${pull_policy}
    container_name: ${jellyfin_container_name}
    restart: ${restart}
    networks:
      - caddy
    ports:
      - ${jellyfin_port_8096}:8096
    environment: 
      - UID=1000
      - GID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/jellyfin/config:/config
      - media_tvshows:/data/tvshows
      - media_movies:/data/movies
    devices:
      - /dev/dri:/dev/dri

  navidrome:
    image: deluan/navidrome:latest@sha256:2ae037d464de9f802d047165a13b1c9dc2bdbb14920a317ae4aef1233adc0a3c
    user: 1000:1000
    pull_policy: ${pull_policy}
    container_name: ${navidrome_container_name}
    restart: ${restart}
    networks:
      - caddy
    ports:
      - "${navidrome_port_4533}:4533"
    environment:
      - ND_SCANNER_PURGEMISSING=full
    volumes:
      - /docker/${navidrome_container_name}/data:/data
      - media_music:/music:ro