---
#networks:

volumes:
  jellyfin_config:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${jellyfin_container_name}/config"
  media_tvshows:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/tvshows"
  media_movies:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/movies"


#secrets:

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    pull_policy: ${pull_policy}
    container_name: ${jellyfin_container_name}
    restart: ${restart}
    ports:
      - ${jellyfin_port_8096}:8096
    environment: 
      - UID=1000
      - GID=1000
      - TZ=America/Chicago
    volumes:
      - jellyfin_config:/config # Configuration directory
      - media_tvshows:/data/tvshows # Media directory
      - media_movies:/data/movies # Media directory
    devices:
      - /dev/dri:/dev/dri


