---
networks:
  mediarr:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.20.20.0/24

volumes:
  media_tvshows:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/tvshows"
  media_movies:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/movies"
  jellyfin_config:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${jellyfin_container_name}/config"
  prowlarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${prowlarr_container_name}/config"


#secrets:

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest@sha256:dc7e75b48d038185216e00029c60a7860c557a0563811934d4870c875467ea8a
    pull_policy: ${pull_policy}
    container_name: ${jellyfin_container_name}
    restart: ${restart}
    networks:
      mediarr:
        ipv4_address: 10.20.20.5
    ports:
      - ${jellyfin_port_8096}:8096
    environment: 
      - UID=1000
      - GID=1000
      - TZ=America/Chicago
    volumes:
      - jellyfin_config:/config # Configuration directory
      - media_tvshows:/data/tvshows # Media directory
      - media_movies:/data/movies # Media directory
    devices:
      - /dev/dri:/dev/dri

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    pull_policy: ${pull_policy}
    container_name: ${prowlarr_container_name}
    restart: ${restart}
    networks:
      mediarr:
        ipv4_address: 10.20.20.10
    ports:
      - ${prowlarr_port_9696}:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - prowlarr_config:/config


