---
#networks:

volumes:
  matrix-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${matrix_container_name}"

#secrets:

services:
  matrix-synapse:
    image: docker.io/matrixdotorg/synapse:latest@sha256:3a002f2771cf9433eb5a6bd25f9f0e3e06f44010e74c2a990f9d7c44a1c955bc
    container_name: ${matrix_container_name}
    restart: ${restart}
    ports:
      - "${matrix_port_8008}:8008"
    environment:    
      - TZ=${timezone}
    volumes:
      - matrix-nfs:/data

