---
#networks:

volumes:
  matrix-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${matrix_container_name}"

#secrets:

services:
  matrix-synapse:
    image: docker.io/matrixdotorg/synapse:latest@sha256:a9e40d0dbec50c34e7370e724b8ed2d57728670dc1304ec04660d854df87ef3c
    container_name: ${matrix_container_name}
    restart: ${restart}
    ports:
      - "${matrix_port_8008}:8008"
    environment:    
      - TZ=${timezone}
    volumes:
      - matrix-nfs:/data

