---
#networks:

volumes:
  matrix-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${matrix_container_name}"

#secrets:

services:
  matrix-synapse:
    image: docker.io/matrixdotorg/synapse:latest@sha256:c8f2742b90ff8777bdfacadf849bc4cdd071fe86770b378cc7700c0ce153d863
    container_name: ${matrix_container_name}
    restart: ${restart}
    ports:
      - "${matrix_port_8008}:8008"
    environment:    
      - TZ=${timezone}
    volumes:
      - matrix-nfs:/data

