---
#networks:

volumes:
  matrix-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${matrix_container_name}"

#secrets:

services:
  matrix-synapse:
    image: docker.io/matrixdotorg/synapse:latest@sha256:10fb7c462957bb076ac4bdca9f1bebaa1c9d31e8bc6d0315551ef0679be7efc5
    container_name: ${matrix_container_name}
    restart: ${restart}
    ports:
      - "${matrix_port_8008}:8008"
    environment:    
      - TZ=${timezone}
    volumes:
      - matrix-nfs:/data

