---
services:
  freshrss:
    image: freshrss/freshrss@sha256:ac8ba074707a020b1a865ae6671f17b6110068142484cee9f36df02ed6c41130
    pull_policy: ${pull_policy}
    container_name: ${container_name}
    environment:    
      TZ: ${timezone}
      CRON_MIN: '2,32'
      FRESHRSS_ENV: development
      env_file:
        - "/env_file/freshrss.env"
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
    volumes:
      - ${sftp_mnt}${container_name}:${app_work_dir}
      - /data/sftp/secrets/environment/freshrss:/env_file # brings in secrets into env file into container directory
    ports:
      - ${freshrss_port}
    restart: ${restart}

