---
services:
  freshrss:
    image: freshrss/freshrss@sha256:ac8ba074707a020b1a865ae6671f17b6110068142484cee9f36df02ed6c41130
    pull_policy: ${pull_policy}
    container_name: ${container_name}
    secrets:
      - freshrss_base_url
      - freshrss_admin_email
      - freshrss_admin_password
      - freshrss_admin_api_password
    environment:
      # add secrets to enviroments
      BASE_URL_FILE: /run/secrets/freshrss_base_url
      ADMIN_EMAIL_FILE: /run/secrets/freshrss_admin_email
      ADMIN_PASSWORD_FILE: /run/secrets/freshrss_admin_password
      ADMIN_API_PASSWORD_FILE: /run/secrets/freshrss_admin_api_password 
      # set env vars 
      TZ: ${timezone}
      CRON_MIN: '2,32'
      FRESHRSS_ENV: development
      # install settings
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
    volumes:
      - ${sftp_mnt}${container_name}:${app_work_dir}
    ports:
      - ${freshrss_port}
    restart: ${restart}
secrets:
  freshrss_base_url:
    file: ~/secrets/environment/freshrss_base_url.txt
  freshrss_admin_email:
    file: ~/secrets/environment/freshrss_admin_email.txt
  freshrss_admin_password:
    file: ~/secrets/environment/freshrss_admin_password.txt
  freshrss_admin_api_password:
    file: ~/secrets/environment/freshrss_admin_api_password.txt
