include:
  - path: docker-compose.real.yml
    env_file:
       - ../global-interp.env
       - local-interp.env
       - ../../../../../data/sftp/secrets/environment/freshrss.env #to pull from local host
