---
include:
  - ../components/caddy_network.yaml

#networks:

volumes:
  media_tvshows:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/tvshows"
  media_movies:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/movies"
  media_music:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/music"
  media_anime:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE_MEDIA}/anime"

#secrets:

services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest@sha256:a370e506348d3f796da3ef5c3519fc2183541c20ca4f082f0804c696f289a048
    pull_policy: ${pull_policy}
    container_name: ${homarr_container_name}
    restart: ${restart}
    networks:
      caddy:
        ipv4_address: 30.30.30.5
    ports:
      - ${homarr_port_7575}:7575
    environment:
      - SECRET_ENCRYPTION_KEY=8aaca723973dd7ea0495d56dc5000eeda8d194f51de7611571dbfab032e39c82
    volumes:
      - /docker/${homarr_container_name}/appdata:/appdata

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest@sha256:a21a912c708cfd3352ec25f00155cb52d486bfd3d1b440e59a042373b3a271e6
    pull_policy: ${pull_policy}
    container_name: ${jellyfin_container_name}
    restart: ${restart}
    networks:
      caddy:
        ipv4_address: 30.30.30.10
    ports:
      - ${jellyfin_port_8096}:8096
    environment: 
      - UID=1000
      - GID=1000
      - TZ=America/Chicago
    volumes:
      - /docker/jellyfin/config:/config
      - media_tvshows:/data/tvshows
      - media_movies:/data/movies
      - media_anime:/data/anime
    devices:
      - /dev/dri:/dev/dri

  navidrome:
    image: deluan/navidrome:latest@sha256:2ae037d464de9f802d047165a13b1c9dc2bdbb14920a317ae4aef1233adc0a3c
    user: 1000:1000
    pull_policy: ${pull_policy}
    container_name: ${navidrome_container_name}
    restart: ${restart}
    networks:
      caddy:
        ipv4_address: 30.30.30.15
    ports:
      - "${navidrome_port_4533}:4533"
    environment:
      - ND_SCANNER_PURGEMISSING=full
    volumes:
      - /docker/${navidrome_container_name}/data:/data
      - media_music:/music:ro