---
#networks:

#volumes:

#secrets:

services:
  freshrss:
    image: freshrss/freshrss@sha256:9a56be99f3927cc8fab4c6bbd5723ae098824792d4d98a84007a95eb64e8f905
    pull_policy: ${pull_policy}
    container_name: ${freshrss_container_name}
    restart: ${restart}
    ports:
      - ${freshrss_port}
    environment:    
      TZ: ${timezone}
      CRON_MIN: '2,32'
      FRESHRSS_ENV: development
      # telling the enviroments "name"_FILE where to pull the secret text from inside of container
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
    volumes:
      - ${share_mnt}${freshrss_container_name}:/var/www/FreshRSS/data

