---
#networks:

#volumes:
volumes:
  caddy_data:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${caddy_container_name}/data"
  caddy_config:
    driver: local
    driver_opts:
      type: nfs
      o: ${NFS_O}
      device: ":${NFS_DEVICE}/${caddy_container_name}/data"
#secrets:

services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare@sha256:4a3d4afed443f026040cad84b48ef2eef6cc6eb5a80a3ecab66a03df469a46f8
    pull_policy: ${pull_policy}
    container_name: ${caddy_container_name}
    restart: ${restart}
    network_mode: host
    ports:
      - "${caddy_port_80}:80"
      - "${caddy_port_443}:443"
      - "${caddy_port_443}:443/udp"
    environment:    
      - TZ=${timezone}
      - BASE_DOMAIN=${CADDY_BASE_DOMAIN}
      - BASE_DOMAIN2=${CADDY_BASE_DOMAIN2}
      - CLOUDFLARE_API_TOKEN=${CADDY_CLOUDFLARE_API}
      - CADDY_NEXTCLOUD_DOMAIN=${CADDY_NEXTCLOUD_DOMAIN}
      - DOCKER_LXC_IP=${docker_lxc_ip}     
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

