---
include:
  - ../components/caddy_network.yaml

#volumes:

#secrets:

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest@sha256:c8e04b9319257448fa4e7ad140cb6596994217ec83d6e7656ccba649bf557318 #https://github.com/open-webui/open-webui/pkgs/container/open-webui/526750706?tag=latest
    pull_policy: ${pull_policy}
    container_name: ${openwebui_container_name}
    restart: ${restart}
    networks:
      - caddy
    ports:
      - "${openwebui_port_8080}:8080"
    environment: 
      - 'OLLAMA_BASE_URL=https://ollama.zacarrie.com'
    volumes:
      - /${docker_dir}/${openwebui_container_name}/data:/app/backend/data
