---
#networks:

volumes:
  open-webui:
#secrets:

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest@sha256:5c75d3cc7ff9c199c07e157ae7710370e2b698979a70a64639ead03b7cf4c679 #https://github.com/open-webui/open-webui/pkgs/container/open-webui/526750706?tag=latest
    pull_policy: ${pull_policy}
    container_name: ${openwebui_container_name}
    restart: ${restart}
    ports:
      - "${openwebui_port_8080}:8080"
    environment: 
      - 'OLLAMA_BASE_URL=https://ollama.zacarrie.com'
    volumes:
      - open-webui:/app/backend/data


