---
#networks:

volumes:
  open-webui:
#secrets:

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest@sha256:c77fa8da6d702ed064b36d414a9493e0bc5242d9a5a3ea0828c5013cbf35b1d5 #https://github.com/open-webui/open-webui/pkgs/container/open-webui/526750706?tag=latest
    pull_policy: ${pull_policy}
    container_name: ${openwebui_container_name}
    restart: ${restart}
    ports:
      - "${openwebui_port_8080}:8080"
    environment: 
      - 'OLLAMA_BASE_URL=https://ollama.zacarrie.com'
    volumes:
      - open-webui:/app/backend/data


