---
#networks:

volumes:
#  frigate_config:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: ${NFS_O}
#      device: ":${NFS_DEVICE}/${frigate_container_name}/config"
#  frigate_storage:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: ${NFS_O}
#      device: ":${NFS_DEVICE}/${frigate_container_name}/media"

#secrets:

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    pull_policy: ${pull_policy}
    container_name: ${frigate_container_name}
    restart: ${restart}
    privileged: true
    stop_grace_period: 30s
    shm_size: "4gb"
    network_mode: host
    #ports:
    #  - "${frigate_container_port8971}:8971"
    #  - "${frigate_container_port5000}:5000"
    #  - "${frigate_container_port1984}:1984" 
    #  - "${frigate_container_port8554}:8554" # RTSP feeds
    #  - "${frigate_container_port8555}:8555/tcp" # WebRTC over tcp
    #  - "${frigate_container_port8555}:8555/udp" # WebRTC over udp 
    environment: 
      - LIBVA_DRIVER_NAME=radeonsi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/frigate/config:/config
      - /data/frigate/recording:/media/frigate
      #- type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #  target: /tmp/cache
      #  tmpfs:
      #    size: 1000000000
    devices:
      #- /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 


