---
networks:
  nginx_network:
    name: nginx_network
    external: true

#volumes:

#secrets:

services:
  freshrss:
    image: freshrss/freshrss@sha256:ac8ba074707a020b1a865ae6671f17b6110068142484cee9f36df02ed6c41130
    pull_policy: ${pull_policy}
    container_name: ${container_name}
    restart: ${restart}
    networks:
      nginx_network:
        ipv4_address: ${freshrss_ipv4}
    ports:
      - ${freshrss_port}
    environment:    
      TZ: ${timezone}
      CRON_MIN: '2,32'
      FRESHRSS_ENV: development
      # telling the enviroments "name"_FILE where to pull the secret text from inside of container
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
    volumes:
      - ${share_mnt}${container_name}:/var/www/FreshRSS/data

